### ISSUE TITLE
Midterm part 2 complete

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#10]

**Comment by cethenmc** [comment]
Nicely done!  The only critique is your double if in the final else section.  Although it will work it will evaluate both "if" statements in there every it falls in (versus an if/else).  Additionally, creating a static loop is one extra line than required.  You could have just multiplied the string by 25 and added the \n.  I will not take off points for these since you satisfied all of the requirements.  33/33
