### ISSUE TITLE
Midterm part 3 complete

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#11]
Spent the entire day trying to figure out what was happening here, tried so many ways of slicing data, in the end gave up and just decided to get the output correct.
I don't know what we were expected to study to do this but i have probably spent a solid 6 hours reading over our stuff and googling slicing and couldn't figure out a better method.

**Comment by cethenmc** [comment]
Thanks for the effort on this part.  I enjoyed your use of rstrip(), and I am certain you came up with that one on your own versus directly through the material offered in this class.  However, the core requirements were missed in areas.  Variables should exist for each letter in 4 (a through e), and each should be created with a single slice (8 pts).  You bypassed using the reverse direction when using indices to get the words for 4e (2 pts).  It was an interesting choice to use a tuple for the quote variable.  We do not use tuples too often, but obviously it does work with the join that you used successfully.  One final note, please do note use absolute paths when saving the file you our opening into the same weekly folder.  Please just use the file name.  I have to clear your path in order to run your file when you use an absolute path.  Thanks, in advance, for your cooperation.  24/34.
