### ISSUE TITLE
Week 10 Subprocess finished

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#13]
I still don't get if we're suppose to use all of the arguments for PS, -a was the cleanest, you can use the others excluding -o that throws a error even outside of a script.

**Comment by cethenmc** [comment]
Pretty well done overall.  6.4 of 8 recorded for now, and you can resubmit soon with corrections for full credit.

Your script should return the same values as if you executed **'ps -axco command'** from the command line (plus a count at the end).  The o does not throw any errors as long as it is accompanied by the 'command'.

switch line 5 to include all three components in your list in the run function call:
     **['ps', '-axco', 'command']**

Also, your count is short by 1 due to an error in the way you are slicing.

I will also add that you do not need to use the range and then use an i.  A simpler for loop where you just print the line would suffice.

![image](https://user-images.githubusercontent.com/112707666/202348194-d9f635a6-cad8-4a77-9c2f-e7f7a1637d2e.png)
